function data()
return {
	en = {
		["mod_name"] = "Sk-signalling system",
		["mod_desc"] = "Das H/v-Lichtsignalsystem im Einsatz bei der DB ab 1948. Außerdem enthalten sind die Bauformen ab 1951 und 1959, auch als Signalbrücken und Vorsignale. Enthalten sind Signale, Wegpunkte und Assets.",
		
        ["H/v 69 Signale der Einheitsbauform"] = "H/v 69 Signale der Einheitsbauform",
        ["Signalbrückenausleger"] = "Signalbrückenausleger",
        ["Linksseitige Signale"] = "Linksseitige Signale",
        ["Zs3/Zs3v"] = "Zs3/Zs3v",
        ["Zs2/Zs2v"] = "Zs2/Zs2v",
        ["Vorsignalwiederholer"] = "Vorsignalwiederholer",
        ["Sh 1"] = "Sh 1",
        ["Zs 1"] = "Zs 1",
        ["Zs 6"] = "Zs 6",
        ["Zs 7"] = "Zs 7",
        ["Wegpunkte"] = "Wegpunkte",
        ["Endlosmodus"] = "Endlosmodus",
		
		
        ["str_rechts"] = "\n- Rechts -",
        ["strB_rechts"] = " Das Signal befindet sich rechts vom Gleis.",
        ["str_links"] = "\n- Links -",
        ["strB_links"] = " Das Signal befindet sich links vom Gleis.",
		
        ["str_asig_69_5_1"] = "Asig 5,1m",
        ["str_asig_69_5_6"] = "Asig 5,6m",
        ["str_asig_kp"] = "Asig Kompakt",
        ["strB_asig_kp"] = "Asig in Kompaktbauform",
        ["str_asig_59_klein"] = "Asig 59 klein",
        ["strB_asig_59_klein"] = "keines Asig in H/V 59 Ausführung",
        ["str_asig_59_gross"] = "Asig 59 groß",
        ["strB_asig_59_gross"] = "großes Asig in H/V 59 Ausführung",
        ["str_bksig"] = "Bksig",
        ["str_msig_v1"] = "Msig V1",
        ["strB_msig_v1"] = "Msig mit anderer Lämpchenanordnung",
        ["str_msig_v2"] = "Msig V2",
        ["strB_msig_v2"] = "Msig mit anderer Lämpchenanordnung",
        ["str_vsig_69"] = "Vsig 69-Schirm",
        ["str_vsig_rund1"] = "Vsig Rund V1",
        ["str_vsig_rund2"] = "Vsig Rund V2",
		
        [" strB_mschild_g_m"] = " Das Mastschild ist zweigeteilt.",
        [" strB_mschild_g_m_o"] = " Das Mastschild ist zweigeteilt und hat einen weißen Rahmen.",
		
        ["strB_mschild_g_g"] = " Das Mastschild ist groß und gelb.",
        [" strB_mschild_g_g_o"] = " Das Mastschild ist groß, gelb und hat einen weißen Rahmen.",
        ["strB_mschild_m_g"] = " Das Mastschild ist klein und gelb.",
        ["strB_mschild_m_g_o"] = " Das Mastschild ist klein, gelb und hat einen weißen Rahmen.",
		
        [" strB_mschild_g_r"] = " Das Mastschild ist groß und rot.",
        [" strB_mschild_g_r_o"] = " Das Mastschild ist groß, rot und hat einen weißen Rahmen.",
        [" strB_mschild_m_r"] = " Das Mastschild ist klein und rot.",
        [" strB_mschild_m_r_o"] = " Das Mastschild ist klein, rot und hat einen weißen Rahmen.",
		
        ["str_unten_x"] = "",
        ["strB_unten_x"] = "",
        ["str_unten"] = "\n(unten)",
        ["strB_unten"] = " Es befinden sich nur am unteren Rand des Signalschirmes Lämpchen.",
		
        ["str_wdh_x"] = "",
        ["strB_wdh_x"] = "",
        ["str_wdh"] = " wdh",
        ["strB_wdh"] = " Es handelt sich um einen Wiederholer.",
		
        ["str_zs1"] = "Zs1",
        ["str_sh1"] = "Sh1",
        ["str_kl"] = "KL",
        ["strB_kl"] = "Kennlicht",
        ["str_hp0"] = "Hp0",
        ["str_sk1"] = "Sk1",
        ["str_sk2"] = "Sk2",
		
        ["str_sh1_kl_only"] = " - nur Sh1/KL",
        ["str_sh1_only"] = " - nur Sh1",
        ["str_kein_sh1"] = " - keine Sh1 Optik",
        ["strB_kein_sh1"] = " Es fehlt die Sh1-Optik.",
		
        ["str_zs6_x"] = "",
        ["str_zs6"] = ", Zs6",
		
        ["str_zs3_x"] = "",
        ["str_zs3_2"] = ", Zs3: 20",
        ["str_zs3_3"] = ", Zs3: 30",
        ["str_zs3_4"] = ", Zs3: 40",
        ["str_zs3_5"] = ", Zs3: 50",
        ["str_zs3_6"] = ", Zs3: 60",
        ["str_zs3_7"] = ", Zs3: 70",
        ["str_zs3_8"] = ", Zs3: 80",
        ["str_zs3_9"] = ", Zs3: 90",
        ["str_zs3_10"] = ", Zs3: 100",
        ["str_zs3_11"] = ", Zs3: 110",
        ["str_zs3_12"] = ", Zs3: 120",
        ["str_zs3_13"] = ", Zs3: 130",
        ["str_zs3_14"] = ", Zs3: 140",
        ["str_zs3_15"] = ", Zs3: 150",
		
        ["str_zs3v_x"] = "",
        ["str_zs3v_2"] = ", Zs3v: 20",
        ["str_zs3v_3"] = ", Zs3v: 30",
        ["str_zs3v_4"] = ", Zs3v: 40",
        ["str_zs3v_5"] = ", Zs3v: 50",
        ["str_zs3v_6"] = ", Zs3v: 60",
        ["str_zs3v_7"] = ", Zs3v: 70",
        ["str_zs3v_8"] = ", Zs3v: 80",
        ["str_zs3v_9"] = ", Zs3v: 90",
        ["str_zs3v_10"] = ", Zs3v: 100",
        ["str_zs3v_11"] = ", Zs3v: 110",
        ["str_zs3v_12"] = ", Zs3v: 120",
        ["str_zs3v_13"] = ", Zs3v: 130",
        ["str_zs3v_14"] = ", Zs3v: 140",
        ["str_zs3v_15"] = ", Zs3v: 150",
	},
	de = {
		["mod_name"] = "Sk-Signalsystem",
		["mod_desc"] = "Die Signalkombination (Sk) ist ein testweise entwickeltes Signalsystem der Deutschen Bundesbahn aus den 1970er Jahren. Statt wie beim H/V-System für Haupt- und Vorsignalbegriff an einem Mast getrennte Signalschirme zu verwenden, wird bei den Sk-Signalen lediglich ein Signalschirm gebraucht. Für die Hauptsignale behielt man die bisherigen Signalschirme bei; reine Sk-Vorsignale sind in Fahrtrichtung Donauwörth mit rechteckigen Signalschirmen ausgestattet; in der Gegenrichtung werden runde Signalschirme verwendet.",
		
        ["H/v 69 Signale der Einheitsbauform"] = "H/v 69 Signale der Einheitsbauform",
        ["Signalbrückenausleger"] = "Signalbrückenausleger",
        ["Linksseitige Signale"] = "Linksseitige Signale",
        ["Zs3/Zs3v"] = "Zs3/Zs3v",
        ["Zs2/Zs2v"] = "Zs2/Zs2v",
        ["Vorsignalwiederholer"] = "Vorsignalwiederholer",
        ["Sh 1"] = "Sh 1",
        ["Zs 1"] = "Zs 1",
        ["Zs 6"] = "Zs 6",
        ["Zs 7"] = "Zs 7",
        ["Wegpunkte"] = "Wegpunkte",
        ["Endlosmodus"] = "Endlosmodus",
		
		
        ["str_rechts"] = "\n- Rechts -",
        ["strB_rechts"] = " Das Signal befindet sich rechts vom Gleis.",
        ["str_links"] = "\n- Links -",
        ["strB_links"] = " Das Signal befindet sich links vom Gleis.",
		
        ["str_asig_69_5_1"] = "Asig 5,1m",
        ["str_asig_69_5_6"] = "Asig 5,6m",
        ["str_asig_kp"] = "Asig Kompakt",
        ["strB_asig_kp"] = "Asig in Kompaktbauform",
        ["str_asig_59_klein"] = "Asig 59 klein",
        ["strB_asig_59_klein"] = "keines Asig in H/V 59 Ausführung",
        ["str_asig_59_gross"] = "Asig 59 groß",
        ["strB_asig_59_gross"] = "großes Asig in H/V 59 Ausführung",
        ["str_bksig"] = "Bksig",
        ["str_msig_v1"] = "Msig V1",
        ["strB_msig_v1"] = "Msig mit anderer Lämpchenanordnung",
        ["str_msig_v2"] = "Msig V2",
        ["strB_msig_v2"] = "Msig mit anderer Lämpchenanordnung",
        ["str_vsig_69"] = "Vsig 69-Schirm",
        ["str_vsig_rund1"] = "Vsig Rund V1",
        ["str_vsig_rund2"] = "Vsig Rund V2",
		
        [" strB_mschild_g_m"] = " Das Mastschild ist zweigeteilt.",
        [" strB_mschild_g_m_o"] = " Das Mastschild ist zweigeteilt und hat einen weißen Rahmen.",
		
        ["strB_mschild_g_g"] = " Das Mastschild ist groß und gelb.",
        [" strB_mschild_g_g_o"] = " Das Mastschild ist groß, gelb und hat einen weißen Rahmen.",
        ["strB_mschild_m_g"] = " Das Mastschild ist klein und gelb.",
        ["strB_mschild_m_g_o"] = " Das Mastschild ist klein, gelb und hat einen weißen Rahmen.",
		
        [" strB_mschild_g_r"] = " Das Mastschild ist groß und rot.",
        [" strB_mschild_g_r_o"] = " Das Mastschild ist groß, rot und hat einen weißen Rahmen.",
        [" strB_mschild_m_r"] = " Das Mastschild ist klein und rot.",
        [" strB_mschild_m_r_o"] = " Das Mastschild ist klein, rot und hat einen weißen Rahmen.",
		
        ["str_unten_x"] = "",
        ["strB_unten_x"] = "",
        ["str_unten"] = "\n(unten)",
        ["strB_unten"] = " Es befinden sich nur am unteren Rand des Signalschirmes Lämpchen.",
		
        ["str_wdh_x"] = "",
        ["strB_wdh_x"] = "",
        ["str_wdh"] = " wdh",
        ["strB_wdh"] = " Es handelt sich um einen Wiederholer.",
		
        ["str_zs1"] = "Zs1",
        ["str_sh1"] = "Sh1",
        ["str_kl"] = "KL",
        ["strB_kl"] = "Kennlicht",
        ["str_hp0"] = "Hp0",
        ["str_sk1"] = "Sk1",
        ["str_sk2"] = "Sk2",
		
        ["str_sh1_kl_only"] = " - nur Sh1/KL",
        ["str_sh1_only"] = " - nur Sh1",
        ["str_kein_sh1"] = " - keine Sh1 Optik",
        ["strB_kein_sh1"] = " Es fehlt die Sh1-Optik.",
		
        ["str_zs6_x"] = "",
        ["str_zs6"] = ", Zs6",
		
        ["str_zs3_x"] = "",
        ["str_zs3_2"] = ", Zs3: 20",
        ["str_zs3_3"] = ", Zs3: 30",
        ["str_zs3_4"] = ", Zs3: 40",
        ["str_zs3_5"] = ", Zs3: 50",
        ["str_zs3_6"] = ", Zs3: 60",
        ["str_zs3_7"] = ", Zs3: 70",
        ["str_zs3_8"] = ", Zs3: 80",
        ["str_zs3_9"] = ", Zs3: 90",
        ["str_zs3_10"] = ", Zs3: 100",
        ["str_zs3_11"] = ", Zs3: 110",
        ["str_zs3_12"] = ", Zs3: 120",
        ["str_zs3_13"] = ", Zs3: 130",
        ["str_zs3_14"] = ", Zs3: 140",
        ["str_zs3_15"] = ", Zs3: 150",
		
        ["str_zs3v_x"] = "",
        ["str_zs3v_2"] = ", Zs3v: 20",
        ["str_zs3v_3"] = ", Zs3v: 30",
        ["str_zs3v_4"] = ", Zs3v: 40",
        ["str_zs3v_5"] = ", Zs3v: 50",
        ["str_zs3v_6"] = ", Zs3v: 60",
        ["str_zs3v_7"] = ", Zs3v: 70",
        ["str_zs3v_8"] = ", Zs3v: 80",
        ["str_zs3v_9"] = ", Zs3v: 90",
        ["str_zs3v_10"] = ", Zs3v: 100",
        ["str_zs3v_11"] = ", Zs3v: 110",
        ["str_zs3v_12"] = ", Zs3v: 120",
        ["str_zs3v_13"] = ", Zs3v: 130",
        ["str_zs3v_14"] = ", Zs3v: 140",
        ["str_zs3v_15"] = ", Zs3v: 150",
	}
}
end
